---
- name: Instalar pacotes
  hosts: all
  tasks: 
    - name: Instalando pacotes
      apt: 
       name: "{{ item }}"
       state: present
      with_items:
       - vim
       - nanosl
       - ccze
       - dnsutils

  
